-- Active: 1761870270745@@127.0.0.1@3306@stranger_drug
CREATE DATABASE IF NOT EXISTS stranger_drug;

USE stranger_drug;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(225) NOT NULL UNIQUE,
    password VARCHAR(225) NOT NULL,
    birthdate DATE NOT NULL,
    role ENUM('ADMIN', 'CLIENTE') NOT NULL
);

CREATE TABLE MODELS(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    biography TEXT NOT NULL,
    photo_url VARCHAR(225) NOT NULL 
);

CREATE TABLE VIDEOS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    s3_bucket VARCHAR(150) NOT NULL,
    s3_key VARCHAR(300) NOT NULL,
    video_type ENUM('MAIN', 'PREVIEW') NOT NULL
);


CREATE TABLE PURCHASES(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    buyer_user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    video_id BIGINT NOT NULL,
    price_paid DECIMAL NOT NULL,

    FOREIGN KEY (buyer_user_id) REFERENCES USERS(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (video_id) REFERENCES VIDEOS(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE NOTIFICATIONS(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    message TEXT NOT NULL,
    purchase_id BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    receiver_user_id BIGINT NOT NULL,

    FOREIGN KEY (purchase_id) REFERENCES PURCHASES(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (sender_user_id) REFERENCES USERS(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (receiver_user_id) REFERENCES USERS(id) ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE SECTIONS(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT NOT NULL
);

CREATE TABLE POSTS(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    main_video_id BIGINT NOT NULL,
    preview_video_id BIGINT NOT NULL,
    section_id BIGINT,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    duration_minutes INT NOT NULL,
    thumbnail_url VARCHAR(225) NOT NULL,

    FOREIGN KEY (main_video_id) REFERENCES VIDEOS(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (preview_video_id) REFERENCES VIDEOS(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (section_id) REFERENCES SECTIONS(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PRICES_POST(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_id BIGINT NOT NULL,
    code_country VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    amount DECIMAL NOT NULL,
    currency VARCHAR(50) NOT NULL,

    FOREIGN KEY (post_id) REFERENCES POSTS(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE POST_MODEL(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_id BIGINT NOT NULL,
    model_id BIGINT NOT NULL,

    FOREIGN KEY (post_id) REFERENCES POSTS(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (model_id) REFERENCES MODELS(id) ON DELETE CASCADE ON UPDATE CASCADE
);