-- Active: 1764023905842@@127.0.0.1@3306@stranger_drug
CREATE DATABASE IF NOT EXISTS stranger_drug;

USE stranger_drug;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE users(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(225) NOT NULL UNIQUE,
    password VARCHAR(225) NOT NULL,
    birthdate DATE NOT NULL,
    role ENUM('ADMIN', 'CLIENTE') NOT NULL
);

CREATE TABLE models(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    biography TEXT NOT NULL,
    photo_url VARCHAR(225) NOT NULL 
);

CREATE TABLE videos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    s3_bucket VARCHAR(150) NOT NULL,
    s3_key VARCHAR(300) NOT NULL,
    s3_url VARCHAR(225),
    video_type ENUM('MAIN', 'PREVIEW') NOT NULL
);

CREATE TABLE purchases(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    buyer_user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    video_id BIGINT NOT NULL,
    price_paid DECIMAL NOT NULL,

    FOREIGN KEY (buyer_user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE notifications(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    message TEXT NOT NULL,
    purchase_id BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    receiver_user_id BIGINT NOT NULL,

    FOREIGN KEY (purchase_id) REFERENCES purchases(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (sender_user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (receiver_user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE sections(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT NOT NULL
);


CREATE TABLE photos(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    s3_bucket VARCHAR(150) NOT NULL,
    s3_key VARCHAR(300) NOT NULL,
    s3_url VARCHAR(225) NOT NULL
);

CREATE TABLE posts(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    main_video_id BIGINT NOT NULL,
    preview_video_id BIGINT NOT NULL,
    section_id BIGINT,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    duration_minutes INT NOT NULL,
    thumbnail_id BIGINT NOT NULL,

    FOREIGN KEY (main_video_id) REFERENCES videos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (preview_video_id) REFERENCES videos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (thumbnail_id) REFERENCES photos(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE prices_post(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_id BIGINT NOT NULL,
    code_country VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    currency VARCHAR(50) NOT NULL,

    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE post_model(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_id BIGINT NOT NULL,
    model_id BIGINT NOT NULL,

    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (model_id) REFERENCES models(id) ON DELETE CASCADE ON UPDATE CASCADE
);